http:
  routers:
    palmr-api:
      rule: "PathPrefix(`/api`)"
      entryPoints:
        - web
      service: palmr-server
      priority: 100
      middlewares:
        - strip-api-prefix

    palmr-web:
      rule: "PathPrefix(`/`)"
      entryPoints:
        - web
      service: palmr-web
      priority: 1

  middlewares:
    strip-api-prefix:
      stripPrefix:
        prefixes:
          - /api

  services:
    palmr-server:
      loadBalancer:
        servers:
          - url: "http://palmr-server:3333"
        passHostHeader: true

    palmr-web:
      loadBalancer:
        servers:
          - url: "http://palmr-web:5487"
        passHostHeader: true
