// Package errors provides HTTP-aware error types that serialise in the
// shape the legacy Node backend used: `{"error": "<message>"}`.
//
// Huma's default ErrorModel is the RFC 7807 problem-details form
// ({title, status, detail}), but the web client matches on
// `data.error` (e.g. `error === "Password required"` to pop the password
// modal). Keeping the legacy shape means the frontend works unchanged.
package errors

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/danielgtaylor/huma/v2"
)

// WriteJSON writes a legacy-compatible JSON error body to a plain
// net/http ResponseWriter. Use this from chi-attached handlers
// (uploads, embed, OAuth-dance) so the frontend gets the same
// `{"error": "..."}` shape it gets from huma handlers.
func WriteJSON(w http.ResponseWriter, status int, msg string) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(map[string]string{"error": msg})
}

// init replaces huma's RFC-7807 default ErrorModel with the legacy
// `{"error": "..."}` shape, so validation 422s (auto-generated by huma
// before any handler runs) also match what the web client expects.
func init() {
	huma.NewError = func(status int, msg string, errs ...error) huma.StatusError {
		// Concatenate validation sub-errors into the same `error` string
		// the Fastify-Zod backend produced.
		if len(errs) > 0 {
			parts := make([]string, 0, len(errs)+1)
			if msg != "" {
				parts = append(parts, msg)
			}
			for _, e := range errs {
				if e != nil {
					parts = append(parts, e.Error())
				}
			}
			msg = strings.Join(parts, "; ")
		}
		return &compatError{Err: msg, status: status}
	}
}

// compatError is a huma.StatusError whose JSON body matches the legacy
// Fastify backend: `{"error": "<message>"}`.
type compatError struct {
	Err    string `json:"error"`
	status int
}

func (e *compatError) Error() string  { return e.Err }
func (e *compatError) GetStatus() int { return e.status }

func mk(status int, msg string) huma.StatusError {
	return &compatError{Err: msg, status: status}
}

func BadRequest(msg string) huma.StatusError   { return mk(400, msg) }
func Unauthorized(msg string) huma.StatusError { return mk(401, msg) }
func Forbidden(msg string) huma.StatusError    { return mk(403, msg) }
func NotFound(msg string) huma.StatusError     { return mk(404, msg) }
func Conflict(msg string) huma.StatusError     { return mk(409, msg) }
func Gone(msg string) huma.StatusError         { return mk(410, msg) }
func Internal(msg string) huma.StatusError     { return mk(500, msg) }
